### ISSUE TITLE
Merging git crates

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-git#114]
It was suggested in Discord that merging the Git crates would ease development and publishing:

> cloudhead
 —  
you don't have to publish 3 crates, only 1, and you don't have to update the versions between all three crates to match
and there's only one version number to track
so I know what state the library is in, vs. having to check three different revisions
not having to publish 3 crates also means you don't have to worry about the order in which you publish the crates..
the only situation in which none of this matters is if you aren't publishing to crates.io
then you just have 1 rev to track
>
> fintohaps
 — 
Today at 2:19 PM
Oh, so you're suggesting having one big crate with all the other crates as modules? That doesn't seem great if, for example, radicle-cob relies on git-ref-format but then also has to pull in radicle-surf
>
> cloudhead
 — 
Today at 2:35 PM
yeah, probably we can merge some of them at least
eg. git-commit + git-trailers + git-ref-format
something like that
and keep surf separate
oh and radicle-git-ext
there's just way too many
>
> fintohaps
 — 
Today at 3:18 PM
Sure, can look into it

One thing to note here is that surf only uses a subset of these -- doesn't use `git-trailers` or `git-commit`. This begs the question, should it depend on the single crates or the mega crate?

**Comment by keepsimple1** [comment]
> One thing to note here is that surf only uses a subset of these -- doesn't use `git-trailers` or `git-commit`. This begs the question, should it depend on the single crates or the mega crate?

I suggest we merge `git-trailers` and `git-commit` into the `radicle-surf` crate for two reasons: 

1. Currently `radicle-surf` does not support trailers in the commit messages. This will bring in a new feature I think it's valuable.
2. `git-commit` crate overlaps with `Commit` type in `radicle-surf`. We can combine them and get rid of the overlapping.

**Comment by cloudhead** [comment]
From the perspective of heartwood:

* radicle-httpd depends on `surf` only
* radicle library depends on `git-ref-format`, `radicle-git-ext`
* radicle-cob depends on `git-trailers`, `git-ref-format`, `git-commit`, `radicle-git-ext`
* radicle-node depends on `git-ref-format`

`git-ref-format` seems to be the most widely used.
`git-trailers` I'm not sure why it even exists, we parse trailers in ~20 lines of code in side `radicle`, using only `git2`, and I would like to get rid of the giant macro in `radicle-cob` which uses it.
`git-commit` and `radicle-git-ext` are very niche, and the latter seems to only be used for the `Oid` type inside of heartwood.

Since all of the crates except `surf` are very small and low on dependencies (except `git-trailers` which pulls in `nom`), one simple solution is to merge them: have a `radicle-git` crate with `git-commit`, `git-ref-format` and `radicle-git-ext`.

**Comment by keepsimple1** [comment]
> `git-trailers` I'm not sure why it even exists, we parse trailers in ~20 lines of code in side `radicle`, using only `git2`, and I would like to get rid of the giant macro in `radicle-cob` which uses it.

Is [this](https://github.com/radicle-dev/heartwood/blob/e7c929898a462aba736864532faef8810dfee466/radicle/src/storage/git.rs#L612-L652) what you are referring to?

**Comment by keepsimple1** [comment]
I've opened a [PR ](https://github.com/radicle-dev/radicle-git/pull/116) to remove `git-trailers`.  Just saw the big macro is already replaced, but I guess my patch still can help and maybe even get rid of [`trailers.rs`](https://github.com/radicle-dev/heartwood/blob/master/radicle-cob/src/trailers.rs) anyway.

**Comment by FintanH** [comment]
# Plan of Action

## Next Steps

So, I think we can create a new crate, also called `radicle-git`, that will contain the following modules:
* `commit` -- all `git-commit` code
* `ref-format` -- all `git-ref-format` code (I'm a little torn on that because it seems like a useful crate in and of itself)
* `ext` -- all `git-ext`, name is debatable so maybe we can see what's useful in there and have multiple modules for them, e.g. `oid`, `error`, etc.

`git-trailers` can be removed once we resolve either https://github.com/radicle-dev/radicle-git/pull/116 or https://github.com/radicle-dev/radicle-git/pull/117.

## Dependencies 

`radicle-surf` will need to be updated to rely on `radicle-git`.

Any `heartwood` crates will need to be updated to use the `radicle-git` crate:
* `radicle`
* `httpd`
* `radicle-cob` will need to be updated to use `git-commit` and not rely on `git-trailers`, after the removal mentioned above.

I'd say we nail these updates down using commit SHAs before we do a release to crates.io.

--

Any thoughts or stuff I'm missing?

**Comment by cloudhead** [comment]
That sounds good to me! I agree about the general usefulness of `git-ref-format`, but given how light `radicle-git` will be, I still think it can be depended on for using `git-ref-format` code.

**Comment by keepsimple1** [comment]
I think `radicle-git-ext` would be a better crate name than `radicle-git` for a couple of reasons: 

1. Indicates they are extensions on top of Git.
2. Indicates they are not a different implementation of Git.

Since `radicle-git-ext` is an existing crate, that would mean we merge others into this crate, instead of creating a new crate.

**Comment by FintanH** [comment]
> I think `radicle-git-ext` would be a better crate name than `radicle-git` for a couple of reasons:
> 
>     1. Indicates they are extensions on top of Git.
> 
>     2. Indicates they are not a different implementation of Git.
> 
> 
> Since `radicle-git-ext` is an existing crate, that would mean we merge others into this crate, instead of creating a new crate.

Ya, I see your point. I'm happy with that :)
