### ISSUE TITLE
radicle-surf: flatten the src/ sub-directories?

### ISSUE THREAD

**Issue by keepsimple1** [radicle-dev/radicle-git#80]
It seems to me that the sub-directories in `radicle-surf/src` are not helping much.

```
├── src
│   ├── diff
│   │   └── git.rs
│   ├── diff.rs
│   ├── file_system
│   │   └── directory.rs
│   ├── file_system.rs
│   ├── git
│   │   ├── branch.rs
│   │   ├── commit.rs
│   │   ├── glob.rs
│   │   ├── history.rs
│   │   ├── namespace.rs
│   │   ├── repo
│   │   │   └── iter.rs
│   │   ├── repo.rs
│   │   ├── stats.rs
│   │   └── tag.rs
│   ├── git.rs
│   ├── lib.rs
│   ├── source
│   │   ├── commit.rs
│   │   ├── object
│   │   │   ├── blob.rs
│   │   │   └── tree.rs
│   │   ├── object.rs
│   │   └── person.rs
│   └── source.rs
````
For example: `file_system/directory.rs` can be fold into `file_system.rs`. 

`git/` directory is not really necessary as everything is based on git anyway. 

`source/`:  I mentioned before, I think it's hard to understand what exactly `source` means here and how it is different from other modules.

`diff/git.rs`: although it's okay to separate this part into its own file, it is not clear from this directory & filename why they are separated from `diff.rs`.

**Comment by FintanH** [comment]
Ya, I think you're right -- I had a similar thought.

> For example: file_system/directory.rs can be fold into file_system.rs.

I think `directory` could move into `lib.rs`. We don't seem to need `file_system` really.

> git/ directory is not really necessary as everything is based on git anyway.
>
> source/: I mentioned before, I think it's hard to understand what exactly source means here and how it is different from other modules.

These two are interesting. I think you're right that it's strange to have a `git` since everything is now `git` based anyway. However, it does seem useful to differentiate it from `source`. Or we completely merge the two, but that requires some upfront work of building a more opinionated browsing experience, for example, a `Directory` (or `Tree`) carries extra metadata such as what was the last commit that touched it.

> diff/git.rs: although it's okay to separate this part into its own file, it is not clear from this directory & filename why they are separated from diff.rs.

The separation was due to multiple VCSs being potentially used. I do like having that extra file defining all the `git2` conversions though.

**Comment by keepsimple1** [comment]
There is one more thing I was thinking of as part of this one: promote `src/object/tree.rs` and `src/object/blob.rs`  to `src/`, and then remove `src/object.rs`. 

The reason is that it is not accurate to have the `object` module consisting of only `blob` and `tree`. There are other types of objects, mainly `commit`. The current [`src/object.rs`](https://github.com/radicle-dev/radicle-git/blob/main/radicle-surf/src/object.rs) does not seem to provide much extra benefits. I would propose to bring `blob.rs` and `tree.rs` under `src/`.

**Comment by FintanH** [comment]
Ya, I see no problem with this :+1:

**Comment by keepsimple1** [comment]
Done from our current point of view.
